export const constants = {
    SET_SEARCH_CITIES_LIST: 'SET_SEARCH_CITIES_LIST',
    SET_SELECTED_CITY: 'SET_SELECTED_CITY',
    SET_SELECTED_CITY_CONDITIONS: 'SET_SELECTED_CITY_CONDITIONS',
    SET_FAVORITES_CITIES: 'SET_FAVORITES_CITIES',
    TOGGLE_TEMPERATUREVALUE_VALUE: 'TOGGLE_TEMPERATUREVALUE_VALUE',
    TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE'
}